# Generated by Django 3.1.7 on 2021-02-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equities',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='finCoins',
            field=models.IntegerField(),
        ),
    ]
