# Generated by Django 3.1.7 on 2021-02-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinApp', '0002_auto_20210225_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=128),
        ),
    ]
