# Generated by Django 3.1.7 on 2021-02-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinApp', '0005_auto_20210225_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
